### ISSUE TITLE
Add generichash module to sodiumoxide

### ISSUE THREAD

**Issue by pbrkr** [sodiumoxide/sodiumoxide#101]
sodiumoxide seems to be missing a generichash module. I can see that some of the generichash functions are defined in libsodium-sys so it should be possible to add these to sodiumoxide. I should be able to write some code for this and submit a merge request but it'd be good to get the API right before I do.

I'm thinking it should provide a hash function with a similar prototype to sodiumoxide::crypto::hash::hash but with modifications as needed. Something like:

```
pub fn hash(in_: &[u8], key: Option<&[u8]>) -> Digest
```

Where key.len() is validated to ensure that they fit into the allowed range of lengths. The digest length can be fixed at crypto_generichash_BYTES (which is 32). Another function could be added later if a variable digest length is needed.

Does that sound like a good way to handle generichash? Or should it support a variable digest length from the start?

**Comment by dnaq** [comment]
Hi,

I think generichash should expose the generic api, we shouldn't fix the length of the `Digest`.

Maybe the best API would be something like?

```rust
pub fn hash(out: &mut [u8], in_: &[u8], k: Option<&[u8]>) -> Result<(), ()>;
```

This also reminds me that I really need to start defining an `Error`-type so that all functions can return meaningful error-values.

I'm not sure of the API though, that's one of the reasons I've been holding off on adding bindings to generichash.

**Comment by betafive** [comment]
I don't think an in-place 'out' argument is very idiomatic. Perhaps:

```
pub fn hash(out_len: usize, in_: &[u8], k: Option<&[u8]>) -> Result<Vec<u8>, ()>;
```

I'm not sure if you can get away with `&[u8]` in the return type so I've said `Vec<u8>` but either will do.

I'd also really like a fixed digest length format. We could have the following wrapper:

```
pub fn hash32(in_: &[u8], k: Option<&[u8]>) -> Result<Digest32, ()>
```

Where `Digest32` is a 32-byte digest defined using the newtype macros.

**Comment by dnaq** [comment]
I'm still a bit sceptical on the wrapper, since the point of generichash is to be generic. Maybe keep `crypto::generichash` similar to the `libsodium` api and add a `crypto::hash::blake2` that uses generichash under the hood and exposes the same API as the rest of the `crypto::hash` functions, but then we diverge from `libsodium`.

As for your other point we could have a `hash` that has your proposed API and a `hash_inplace` that uses an inplace argument. The reason for that is that for generic usage an inplace argument is more helpful. Also in embedded systems we don't want to dynamically allocate memory. That's also why I still keep the `box_inplace` branch open, to expose non-allocating primitives for embedded use.

**Comment by betafive** [comment]
An in-place version would definitely be useful to have. I'll see if I can find some time this week to try implementing something for this.

A fixed length wrapper function is easy to write as needed in application code so it probably doesn't need to go in to sodiumoxide.

**Comment by betafive** [comment]
@dnaq: I've sent a merge request to add bindings for additional generichash functions to libsodium-sys along with adding some really basic tests.

I've implemented `hash` and `hash_inplace` functions but I'm struggling with the testing. My expectation is that if I call `crypto_generichash` with a 32-byte output buffer, a message and no key I will get the first 32 bytes of the BLAKE2b sum of the message. However this isn't what I'm getting.

If I use a 64-byte output buffer I get a BLAKE2b hash which matches the output of the `b2sum` program. If I use a 32-byte buffer the output does not match the first 32 bytes of the output of `b2sum`.

I don't think I'm doing anything wrong as it's just a simple wrapper. I'll need to investigate this further and see if libsodium and/or the reference implementation of BLAKE2b shows this behaviour.

**Comment by dnaq** [comment]
See #103

**Comment by dnaq** [comment]
Please see #203

**Comment by nvesely** [comment]
I didn't see this issue before making #204, but will just copy my comments relevant to the API:

> In sodiumoxide BLAKE2b is only exposed via libsodium_sys. I think that BLAKE2b should be brought into the main sodiumoxide library in a way that directs users to it, recommends it, and makes it the default (through namespacing and documentation). On the other hand, use of SHA2 should not be discouraged, but it should be placed slightly more "out of the way" (e.g., in the libsodium documentation it's placed under "Advanced.") There may be reasons (e.g., compliance) that people still need to use SHA2.

**Comment by danielrangelmoreira** [comment]
Is there anyone working on this issue? I have implemented a partial functioning generic hash module for my toy project that may be useful or be used as a start point for the generic hash and blake module implementation. https://crates.io/crates/rsign

**Comment by noproto** [comment]
I'm curious if libsodium will adopt BLAKE3.

**Comment by kpp** [comment]
Seems like it is done in https://github.com/sodiumoxide/sodiumoxide/pull/196.

Please feel free to reopen the issue if you think we are missing something.
