### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by jimmycuadra** [sodiumoxide/sodiumoxide#132]
Just wanted to register my interest in Sodium Oxide supporting Sodium's [password hashing features](https://download.libsodium.org/libsodium/content/password_hashing/) (particularly Argon2.)

**Comment by zonyitoo** [comment]
Is this issue accepted?

**Comment by sopium** [comment]
I think scrypt is already supported.

I would like to see Argon2 as well, but Argon2 is only available in libsodium 1.0.9 and later. Is that going to be a problem?

How does sodiumoxide deal with features only available in relatively new versions of libsodium, in general?

**Comment by lawliet89** [comment]
One solution is to include the libsodium source code as a submodule for `libsodium-sys` so that the crate is built against that source instead of the library on the user's machine.

See how the [`git2`](https://github.com/alexcrichton/git2-rs/tree/master/libgit2-sys) crate deals with its FFI bindings.

**Comment by kmcallister** [comment]
@lawliet89: I'm very much in favor of having that option. I think it would ease cross-compilation as well.

**Comment by dnaq** [comment]
Please see #203

**Comment by kpp** [comment]
Argon2 #239 is merged
