### ISSUE TITLE
Expose bindings to crypto_secretstream_*()

### ISSUE THREAD

**Issue by jrmuizel** [sodiumoxide/sodiumoxide#201]
This is helpful for supporting data that's larger than will fit in memory

**Comment by dnaq** [comment]
Please see #203

**Comment by cynecx** [comment]
JFYI: I have a **experimental** branch which supports [this](https://github.com/cynecx/sodiumoxide/tree/streaming).

**Comment by jrmuizel** [comment]
What needs to be done to get your branch mergeable?

**Comment by Dylan-DPC** [comment]
@cynecx do you want to merge it? the longer you wait the more conflicts you will end up with

**Comment by nvesely** [comment]
Let's see if @dkulic gets back this week, and if not go from there.

**Comment by dkulic** [comment]
Hi, I am here. I will look for the conflicts.

**Comment by nvesely** [comment]
There are two closed PRs that fix this issue: #222 and #240. #222 was closed because it seemed like there was momentum behind a re-implementation with a different API, but then too many people had problems with the new API implemented in #240 as well. There has been a ridiculous amount of back and forth over the issue, and not much progress has been made with respect to some sort of consensus on an interface.

Personally, I would like someone to implement https://github.com/sodiumoxide/sodiumoxide/pull/240#issuecomment-420765420, and I'd be happy to do it myself. I at least got two thumbs up emojis from core contributors to the project on this proposal, which kind of feels like enough, but due to the continued discussion, I didn't want to risk my time by implementing something that won't be merged and that will just spawn more debate/ discussion. I will only implement something I feel has broad consensus and that I feel is likely to be quickly merged with little modification.

My interest in further discussing interfaces here is pretty low; I've never seen such protracted discussion over such a small feature implementation. If people are not happy with my proposal, I'm totally okay with that, and am happy to let other people continue to work out this issue on their own

**Comment by Dylan-DPC** [comment]
Yeah it is sad to be in a stalemate state where there is no clear advantage by one proposal over the other and there is no clear consensus. 

What we can do is "fastrack" this issue - that is whoever picks up just builds the complete feature without facing any questions (except for bugs during review process). 

If all fine, then any one (including @nvesely if they want) can pick this and go ahead and implement it without stoppages on the design choices. I know we might end up realising the flaws later and rewriting some of the stuff but i think its the best thing to do instead of moving in circles.

**Comment by samscott89** [comment]
Apologies for my part in drawing out the discussion. My intention was to support the overall proposal, but to suggest some alternative namings, which I had hoped would be fairly straightforward yes/no.

For what it's worth, I don't agree it's such a simple/trivial feature to implement. Especially when the goal of a library is to expose safe cryptography -- both in the Rust meaning of type/memory safety, and in terms of crypto misuse. It's not like there are many examples out there of great interfaces... 

I think it would be good to get it right. I'll have a go at putting something together, and try to lay out some of the discussion points.

**Comment by samscott89** [comment]
I've had a go at building out some API options. My starting point was to try and write down a use case, so we could see how the APIs might work in context. So I recreated the [example code from the libsodium docs of file encryption](https://download.libsodium.org/doc/secret-key_cryptography/secretstream#file-encryption-example-code).

You can see the results in this branch: https://github.com/samscott89/sodiumoxide/tree/secretstream-take3

This was building off the work in pr #240 .

In particular, the tests/examples are [here](https://github.com/samscott89/sodiumoxide/blob/secretstream-take3/src/crypto/secretstream/mod.rs#L114).

And the documentation for each is built here: https://samscott89.github.io/sodiumoxide/sodiumoxide/crypto/secretstream/xchacha20poly1305/index.html

----

Some justification for each approach:

The [`low_level`](https://samscott89.github.io/sodiumoxide/sodiumoxide/crypto/secretstream/xchacha20poly1305/low_level/index.html) module is approximately what you would get by just wrapping the API in a simplistic way, with a few Rusty conversions. I.e. using enums for the tag instead of raw `u8`s.

It's pretty unwieldy, with long method signatures. And one choice which would probably need to be whether this takes in a buffer to write to, or returns a `Vec`. Note that here `State` is just a newtype wrapper around the raw pointer, and does not do any checking of whether the stream should be pushing or pulling.

The [`oop`](https://samscott89.github.io/sodiumoxide/sodiumoxide/crypto/secretstream/xchacha20poly1305/oop/index.html) approach would be the next abstraction layer. This provides a `Stream` object which contains the state (`State`), tracks whether the stream is `finalized`, and has a marker trait in `StreamMode` for type safety. This provides a few ergonomics improvements:
 - The `StreamMode` marker trait makes `init_push` followed by `stream.pull(..)` a compile time error. 
 - `push`/`pull` can be called by `stream.push(...)`, which is a bit nicer than passing state as an input
 - Tracking whether `finalized` is set helps avoid mysterious errors.
 - Can do a manual rekeying on dropping the stream to guarantee the key (as stored in memory) is rotated/erased when finished.
 - An additional `finalize` method produces the ciphertext for an empty message, with `Tag::Final` and consumes the stream. Should be used in example usage to ensure the stream is finalized and consumed.

----

At this point, the API seems pretty good. For example, this is the example for encrypting a file:

```rust
fn encrypt_file<T, S>(target: &mut T, source: &mut S, key: &secretstream::Key)
    -> Result<(), MyError>
where
    S: Read,
    T: Write,
{
    let (mut stream, header) = secretstream::init_push(&key)?;
    target.write_all(&header.0)?;
    let mut buf = [0u8; CHUNK_SIZE];
    let mut count = source.read(&mut buf)?;
    while count > 0 {
        let ct = stream.push(&buf[..count], None, Tag::Message)?;
        target.write_all(&ct)?;
        count = source.read(&mut buf)?;
    }
    let ct = stream.finalize(None)?;
    target.write_all(&ct)?;
    Ok(())
}
```

You have to do read -> push -> write, with the middle push allocating each time. This seems unfortunate. Could consider using the `push_buf`, `pull_buf` versions from `low_level` to avoid this.

---

I did some further experiments to try and make the API nicer. But these don't seem to add much:

[`builder_pattern`](https://samscott89.github.io/sodiumoxide/sodiumoxide/crypto/secretstream/xchacha20poly1305/builder_pattern/index.html)
which replaces `stream.push(&msg, None, Tag::Message)?;` by something like `stream.message(&msg).push()?`, and `stream.push(&msg, Some(ad), Tag::Final)` with `stream.message(&msg).ad(ad).tag_final().push()?;`
The idea here was to make the defaults (no AD, and `Tag::Message`) have nicer syntax. But probably overkill.

[`with_traits`](https://samscott89.github.io/sodiumoxide/sodiumoxide/crypto/secretstream/xchacha20poly1305/with_traits/index.html) was an attempt to wrap the `Stream` in something higher level like `Iterator` or `Read`. I don't think any of these were particularly useful in the example above. But it might provoke some ideas/discussion.

---

Overall, I like the `Stream` API given in the `oop` module, which was my interpretation of what @nvesely was suggesting.

**Comment by nvesely** [comment]
I had the same idea for the `init_{pull,push}` methods, but I didn't know if the compiler would accept the function signatures (lines 431 & 436)! I'm glad that you can do that and I like it. Not sure if we should provide two different methods for initializing though (i.e., maybe make the `Stream<{Push,Pull}>::init` methods private).

I don't like the new low level functions which return Vec because they're unecessary, don't support `no_std`, and are less efficient. We could potentially add methods for computing the correct `buf` length, e.g., users could call `let mut buf = [0; stream::buf_size(d)]`, where depending on if `stream` is a `Stream<Push>` or a `Stream<Pull>` it adds or subtracts, respectively, `ABYTES` to or from `d`, where `d` is a message or ciphertext.

`Stream<Push>::finalize` shouldn't take an `ad` method for simplicity. This would also mean the output size is known at compile-time, which could be useful depending on what direction we go regarding my previous comment. I'm also open to just removing this method.

Not a fan of `builder_pattern`. Just seems like a worse interface than `oop`.

I didn't look to close at `with_traits`, but it looks a bit complex and unwieldy. I do still see the value in some of these ideas, but feel like we should just keep it simple unless we see there's a need for such methods. I think it's good not too be too proactive with features unless there's demand in a crypto library.

Also, when you squashed my commits you removed me as an author.

**Comment by nvesely** [comment]
Oh and good work on this :rainbow: :sparkles:

**Comment by samscott89** [comment]
Thanks for the comments. I should say that I went for just dumping everything out to get feedback. For the final version, I agree we should apply your statement:
> I think it's good not too be too proactive with features unless there's demand in a crypto library.

So for most of these we can err on the side of not including, and expose later if there's demand. With the trait stuff, that could even just be in a separate examples repo which we point people towards. Or do the approach that serde takes at times, and link to a closed issue with the example code.

>  Not sure if we should provide two different methods for initializing though (i.e., maybe make the Stream<{Push,Pull}>::init methods private).

Hmm, yeah good point. I like that with the `init_{push,pull}` you don't even need to faff about with the generics etc. So would prefer to keep those. Slight benefit of the typed variants is to allow writing some kind of generic helper functions for consumers. Probably not that useful though, since there is little generic functionality.

> I don't like the new low level functions [...]

Me neither. In hindsight I was conflating two issues. The real issue is whether to offer the ability to encrypt into a buffer and/or to encrypt into a new vec. Either way this should probably be on the oop variant, since I can't see any cases where the low level versions are needed.

You could imagine two use cases. One which is some kind of message encryption. Simply takes messages on a stream (`Vec<u8>`s), does a ratcheted encryption with `push(&msg, None, Tag::Rekey)` and gets a new vec out along the way. Very clean. But for something like streaming encryption of a large file, reusing the buffers is nicer...

> Stream<Push>::finalize shouldn't take an ad method for simplicity. This would also mean the output size is known at compile-time, which could be useful depending on what direction we go regarding my previous comment. I'm also open to just removing this method.

Good plan. I prefer the method over having to write `stream.push(&[], None, Tag::Final)`. And gives a nice way to consume the stream. But it's not a huge deal.

> Not a fan of builder_pattern. Just seems like a worse interface than oop.

Agreed. Seemed like a better idea in my head :stuck_out_tongue: 

> I didn't look to close at with_traits, but it looks a bit complex and unwieldy.

Yeah, just doesn't really make sense of the library to do this. I like the idea of dumping it somewhere as an example for people if desired. Maybe even wrapping it into a single purpose crate... (I'm thinking a `sodiumoxide-filecrypt` which provides a simple function to encrypt large files in chunks, by taking in a `Read`). 

> Oh and good work on this

Thanks! It's primarily your work. Apologies for squashing the merges down. Was a bit of hasty decision to make the branch shorter.

**Comment by nvesely** [comment]
I think a `Stream::new` method which takes no arguments and returns a `(Stream<Push>, Header)` would be a useful convenience vs. generating the key separately and passing it to `Stream::init_push`. Also, I think bringing back `Stream::is_not_finalized` would be good.

I'm against all uses of vec for efficiency (stack vs. heap) and no_std compatibility reasons. One thing that might be good to help correctness in downstream programs is to enforce that `buf` is `± ABYTES` in relation to `c`/`m` in `push` and `pull`, i.e., instead of just ensuring it's large enough, we should ensure it's exactly the correct size. This of course presents no problems in terms of, e.g., decrypting a series of messages to the same array because you just pass in `result[a:b]` as `buf` to decrypt the first message, `result[b:c]` for the second, and so on...

As far as the final version I assume there won't be these sub-modules and you can just combine the code from `low_level` and `oop`, but only expose `Stream`, `Key`, and `Tag`. ` `push` and `finalize` would use `push_buf`, which we could rename `_push` and would be private. A new `pull` would combine the code from `pull` and `pull_buf`.

I wonder if the `private::Sealed` pattern is needed. Why should `StreamMode` be public and wouldn't making it private give the same effect of not allowing further implementations of the trait?

Can you make a new branch off my branch and then cherry-pick your commits from this branch ontop? And then continue with whatever changes?

While we're obviously still discussing a few finer points, I think we agree on the general points and it would be useful to start moving from this exploratory implementation to a "final" (never!) version.

**Comment by dvic** [comment]
Hi @nvesely @samscott89,

I took a stab at this in https://github.com/dvic/sodiumoxide/tree/secretstream.

> I think a `Stream::new` method which takes no arguments and returns a `(Stream<Push>, Header)` would be a useful convenience vs. generating the key separately and passing it to `Stream::init_push`

I went with the key as parameter because this allows you to generate keys in whatever way you need (e.g., like mentioned in the libsodium docs, leveraging the key exchange API or using the password hashing API).

> I'm against all uses of vec for efficiency (stack vs. heap) and no_std compatibility reasons

I'm not sure where the use of vectors can be avoided, please let me know if I'm missing something (I did replace the use of `vec!`, see comment below).

> I wonder if the private::Sealed pattern is needed. Why should StreamMode be public and wouldn't making it private give the same effect of not allowing further implementations of the trait?

I believe this is a common pattern to disallow the implementation of `StreamMode` (while it being public). I did not manage to get the compiler happy with it being private.

> Can you make a new branch off my branch and then cherry-pick your commits from this branch ontop? And then continue with whatever changes?

I refactored the branch of @samscott89 but for now I just branched of the latest master and created a separate commit, losing all history. I'm not sure if cherry picking would work because it's quite a change. Of course I can also apply/merge this patch with any branch, please let me know. I don't want to take any credit for the code I just want to see this API land in the library 😄.

Furthermore, I did change a few things that require attention (I'd love to hear feedback on this):
* using `Vec::with_capacity` with `set_len` instead of `vec![0u8; buf_len];` (I noticed this pattern in existing code in the library)
* for now I did not use the macros approach as there is currently only one implementation, I find the code much more readable in this way.
* The module has a public `gen_key` function (similar to other modules) instead of a static method on `Key`

If this is heading in the right direction I'm willing to check/update the docs and add the missing tests.
