### ISSUE TITLE
Test libsodium on the 5 big platforms

### ISSUE THREAD

**Issue by psivesely** [sodiumoxide/sodiumoxide#233]
- [x] Linux
- [x] Windows
- [x] macOS
- [ ] iOS
- [x] Android

**Comment by Dylan-DPC** [comment]
Test libsodium on the above platforms. If it works well then submit a PR updating the [readme](https://github.com/sodiumoxide/sodiumoxide/blob/master/README.md#platform-compatibiility). If it fails and you can't resolve it, create an issue here.

**Comment by 0e4ef622** [comment]
I got it to compile and run tests on Windows (they all succeeded), although I had to do a lot of fiddling to get the linker to find the library.

**Comment by Dylan-DPC** [comment]
@0e4ef622 Thanks for testing this. 2 things: 

1) Can you elaborate on how you got the linker to find the library? We can add these steps to the readme (you are free to PR that) 

2) Can you help us set up appveyor properly? (See #258).

**Comment by 0e4ef622** [comment]
2 things worked actually, renaming the library from libsodium.lib to sodium.lib, and changing the build script to look for libsodium.lib instead of sodium.lib

**Comment by is2ei** [comment]
Any test scenarios for `iOS` and `Android` ? 
I'd test it if I can.

**Comment by kpp** [comment]
@is2ei Hello. The only one scenario is `cargo build --target ...` on the latest master. If you manage to build a static app and run it on mobiles that would be great. Any simple app would work like:

```
extern crate sodiumoxide;

use sodiumoxide::crypto::box_::gen_nonce;

fn main() {
    let nonce = gen_nonce();
    println!("nonce={:?}", nonce);
}
```

**Comment by tasn** [comment]
Update regarding Android:
I managed to build a rust library for Android and sodiumoxide seems to work!
To get it to build, I had to I had to set CC to the clang from the android NDK, in addition to the normal steps for Android cross-compilation. One gotcha to remember: make sure you are using an NDK that's compatible with the device you are testing on. I used a too-new of an NDK which caused it not to work.

What I tested:
```
extern crate base64;
extern crate sodiumoxide;

use std::os::raw::c_char;
use std::ffi::CString;

use sodiumoxide::crypto::hash;

#[no_mangle]
pub extern fn rust_test() -> *mut c_char {
    sodiumoxide::init().unwrap();

    let data_to_hash = sodiumoxide::randombytes::randombytes(32);
    let digest = hash::hash(&data_to_hash);
    let encoded = base64::encode(digest);

    CString::new(encoded).unwrap().into_raw()
}
```

I'm using the base64 crate because sodiumoxide still doesn't have a released version that exposes the base64 sodium utils.

I plan on trying to properly use it on Android, so will report back if I'm getting any issues, though seems to be fine for now. :)

**Comment by tasn** [comment]
Another Android update: I'm now using it in a real project. It compiles fine to aarch64/armv7a/i686/x86_64 and I tested it on armv7a and it works great!

**Comment by kpp** [comment]
sodiumoxide is tested on Tier 1 platforms. We cannot do better without real consumers on exotic platforms.

Feel free to reopen issue if you think we are missing something.
