### ISSUE TITLE
Support Hexadecimal encoding/decoding from libsodium

### ISSUE THREAD

**Issue by lovesh** [sodiumoxide/sodiumoxide#246]
Libsodium has methods `sodium_bin2hex` and `sodium_hex2bin` for going to and fro between raw bytes and hexadecimal representation. Would folks be interested in bringing them as utilities?

**Comment by nvesely** [comment]
I think this would be good because while there's probably a sufficiently simple and efficient way to do this using the Rust core libraries it probably won't execute in constant-time like the libsodium implementation.

If you have an immediate use case for these functions we could prioritize including it in the next release. Let us know if you want to write the PR, otherwise I would be willing to do it.

**Comment by kpcyrd** [comment]
The rust way would be the [`ToHex`][0] and [`FromHex`][0] traits of the hex crate. We could consider implementing those traits using the libsodium methods for the structs in sodiumoxide in addition to providing access the the function itself.

[0]: https://docs.rs/hex/0.3.2/hex/trait.ToHex.html
[1]: https://docs.rs/hex/0.3.2/hex/trait.FromHex.html

**Comment by lovesh** [comment]
@nvesely Will submit

**Comment by nvesely** [comment]
Awesome! How are you going to do it? Just expose the functions with a more Rust idiomatic interface or implement the hex traits for all the structs? Since lots of structs rely on the same macro code, it could require a lot less effort than you think to do it the latter way.

**Comment by naftulikay** [comment]
This is an awesome idea, and reusing APIs that already exist is a great solution. The usability of sodiumoxide and the security of libsodium are really compelling.

**Comment by lovesh** [comment]
@nvesely I was planning to follow the convention in `src/utils.rs` and expose the functions. In "implement the hex traits for all the structs", which structs are you referring to?

**Comment by nvesely** [comment]
So it probably doesn't make sense for every single struct, but to give some examples, structs that represent keys, digests, and ciphertexts could all implement `ToHex` and `FromHex` from the `hex` crate.

However, I think better than adding a new external crate to this project (which needs to be `no_std`-compatible--I haven't checked), we could just create our own `ToHex` and `FromHex` traits that present a slightly different interface. In particular `FromHex::from_hex` should take an additional `ignore` argument like `sodium_hex2bin` does.

**Comment by nvesely** [comment]
@lovesh I assigned you to denote you're working on this issue. If at any point you're not able to continue working on it for any reason before completion, just let us know and post a link to the work-in-progress branch if possible, and I can take it over.

**Comment by lovesh** [comment]
@nvesely So i can go ahead with exposing the function like in utils.rs or you want me to implement the trait

**Comment by nvesely** [comment]
I think you should write new traits `ToHex` and `FromHex` that are modeled after the traits in the `hex` crate with the same name, with the modification I described above to expose an `ignore` field in `FromHex::from_hex`.

Next implement these two traits for all structs it makes sense to do so for, practice DRY by creating or extending macros. However, before extending a macro used with many structs, make sure to look at each one and make sure the implementation of the trait makes sense for all of those structs, or if a special implementation is needed for either correctness or could provide an opportunity to increase the security and correctness of this crate by providing additional validation. One example of where a generic implementation wouldn't make sense is `crypto::generichash::Digest`:

```
pub struct Digest {
    pub(super) len: usize,
    pub(super) data: [u8; crypto_generichash_BYTES_MAX as usize],
}
```

In order to avoid allocation to the heap and use of `std`, we allocate an array of the maximum byte-length possible for a digest, but only use `len` bytes. We already implemented `AsRef<[u8]>` for `Digest`, which returns a slice of only these `len` bytes, so just use that to get the slice you need to pass to the libsodium function. Likewise, when creating a `Digest` from a hex string you'll need to determine `len` from the hex string. If it is greater than `DIGEST_MAX` or less than `DIGEST_MIN`, the function should fail early and return an `Err(())`. The last `DIGEST_MAX - len` bytes of the `Digest` should be zeros in line with how `crypto::generichash::mod::State::finalize` works.

Hope that was a good example of how you can write implementations of these traits that help catch possible programmer/ user mistakes by using all information we have to define what a correct hash looks like. Whenever you see a similar opportunity, I suggest you take it.

I gave some examples of structs that it does make sense to implement these traits for above, but to give an example of where it doesn't make sense: a struct that holds the internal state of some cryptographic operation. If you're unsure, just ask for feedback here.

**Comment by kurnevsky** [comment]
@nvesely I think the raw function would be useful as well to convert any binary data to/from hex with constant time, not just types from sodiumoxide. So it can be a good first step.

**Comment by nvesely** [comment]
^ True. I think we could merge a basic utility implementation first, and then leave this issue open until we've implemented the traits, if such a PR would be made.

**Comment by lovesh** [comment]
Apologies, this is taking longer. Here is a basic utility added https://github.com/sodiumoxide/sodiumoxide/pull/252

**Comment by kurnevsky** [comment]
@lovesh windows build is broken, that's why appveyor fails. Nothing wrong with your code here.
