### ISSUE TITLE
Necessity of key validation

### ISSUE THREAD

**Issue by HoOngEe** [sodiumoxide/sodiumoxide#414]
Sodiumoxide supports `from_slice`, `deserialize` for `SecretKey` type and `PublicKey` type. I utilized it to reconstruct keys from data read from secure `Keystore` or decoded from messages.
However, I'm worrying about breaking the invariant of the key type because keys are not just arbitrary byte arrays. I want to check the validity of the byte representations before invoking the method like `sign` and `verify`, how can I reach this goal?

**Comment by dnaq** [comment]
Let me quote from the curve25519 paper

“Free key validation. Typical elliptic-curve-Diffie-Hellman functions can
be broken if users do not validate public keys; see, e.g., [14, Section
4.1] and [3].
A hash of the shared secret Curve25519(a, Curve25519(b, 9
 in this paper has size above 2
structures can be broken much more quickly by non-generic algorithms, but
E(Fp2) does not have those structures. See Section 3 of this paper for more
detailed comments on the security of the Curve25519 function.
. Elliptic curves with certain special algebraic

The time for key validation is quite noticeable and usually not reported. In
contrast, every 32-byte string is accepted as a Curve25519 public key.
“

In curve25519 all 32-byte strings are valid secret keys (scalars) and all
32-byte strings are valid public keys. That being said, if you want you can
verify that the scalar isn’t zero, since a zero scalar will lead to a zero
public key.

**Comment by HoOngEe** [comment]
Ok, I understood. I should have specified I'm working on the signature scheme. I read the code and the `Ed25519` paper. I misunderstood the secret key information possess the multiplier applied to the generator so I was worrying the case where a secret key is 256-bit but not a field element.
However, the secret key derives the multiplier in itself so I don't have to validate it; I understood all 32-bytes strings are valid. Thank you for the help!
